// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xckkkqlfldlxddnvpxts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhja2trcWxmbGRseGRkbnZweHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjkzNTksImV4cCI6MjA2NTU0NTM1OX0.3kD6mB2o97MdAfVZkZl2OSmzl7yq0t0n9jLGrxe85_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);